### ISSUE TITLE
"Scheduled Charging" not working since latest update

### ISSUE THREAD

**Issue by teal-z** [snaptec/openWB#2830]
I recently updated my OpenWB series 2 standard+ (from exact prior version unknown, still version 2 tough) to 2024-03-19 06:56:08 +0100 [a6b648645].
Since then the scheduled charging doesn't work anymore. The car gets only charged if there is enough PV power.
It is set to charge 32kWh till 7:00. Checking my homeassistant logs I see, that around 4:00 the openWB tries to to charge the car with 16A. It increases up to 32A at around 5:30. At 7:00 the log states, that the minimum of 6A is not given (I think this is due to low solar power at that time).
So openwb seem to want to charge but actually doesn't. If I switch to Instant Charging the car gets charged immediately.
I double checked all the setting and they seem fine to me.

Any ideas are appreciated :)

**Comment by LKuemmel** [comment]
This is already fixed in current master.

**Comment by teal-z** [comment]
Release 2.1.4 fixed it.

**Comment by teal-z** [comment]
I closed the ticket prematurely. Version 2.1.4 (417a30647) still doesn't actually charge over night, when set to scheduled charging.

**Comment by LKuemmel** [comment]
This is the repository of version 1.9. Please post your request in the openWB forum.
